# docker-compose.yml
# Autor: Urtzi
services:
  app: # Servicio principal de la aplicación PHP
    build:
      context: . # Carpeta raíz enviada al build de Docker
      dockerfile: docker/php/Dockerfile # Archivo que define la imagen personalizada de PHP
    container_name: imaw_php_app # Nombre fijo del contenedor para localizarlo rápido
    ports:
      - "8080:80" # Puerto local 8080 -> puerto 80 de Apache dentro del contenedor
    volumes:
      - ./src:/var/www/html # Sincroniza el código local con Apache (desarrollo en caliente)
    depends_on:
      - db # Arranca la BD antes que la app

  db: # Servicio de base de datos relacional
    image: mariadb:11 # Imagen oficial de MariaDB versión 11
    container_name: imaw_mariadb
    restart: unless-stopped # Reinicio automático salvo parada manual
    environment:
      MARIADB_ROOT_PASSWORD: root # Clave root (entorno docente)
      MARIADB_DATABASE: imaw # BD inicial al crear el contenedor
      MARIADB_USER: imaw # Usuario de aplicación
      MARIADB_PASSWORD: imaw # Clave del usuario de aplicación
    ports:
      - "3306:3306" # Exposición opcional para conectar desde herramientas locales
    volumes:
      - db_data:/var/lib/mysql # Persistencia de datos aunque se recree el contenedor

  phpmyadmin: # Interfaz web para administrar la base de datos
    image: phpmyadmin:latest
    container_name: imaw_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db # Host interno: nombre del servicio de BD
      PMA_PORT: 3306 # Puerto interno de MariaDB
    ports:
      - "8081:80" # Acceso a phpMyAdmin desde navegador local
    depends_on:
      - db

  composer: # Herramienta puntual para ejecutar Composer sin instalarlo en Windows
    image: composer:2
    container_name: imaw_composer
    working_dir: /app # Carpeta de trabajo dentro del contenedor
    volumes:
      - ./:/app # Monta todo el proyecto para que composer vea composer.json
    profiles:
      - tools # Solo se ejecuta al invocarlo (run) o activando perfil tools

volumes:
  db_data: # Volumen nombrado para datos persistentes de MariaDB